name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image and push
      working-directory: ./IPRefreshLogger
      run: |
        docker login --username krysztal --password ${{ secrets.DH_PAT }}
        docker build . --tag krysztal/iprefreshlogger:latest
        docker push krysztal/iprefreshlogger:latest
